### ISSUE TITLE
All Authentification methods failed

### ISSUE THREAD

**Issue by AndresJ551** [tomas/rtop#6]
Hola @tomas!
Se ve muy bien el proyecto, solo me falta el punto de autenticar, que desde SSH ingeso sin pass a todos los servidores, sin embargo aún pasando el parámetro -k /root/.ssh/id_rsa me lanza el error del título.

¿Puede ser que se esté ejecutando con otro usuario? En ese caso ¿Cuál sería?

Gracias de antemano!

**Comment by tomas** [comment]
Posiblemente no tengas escuchando el SSH agent en la ruta esperada (`ENV['SSH_AUTH_SOCK']`) o bien no tienes la llave incluida en el keyring (lo revisas/agregas con `ssh-add`). Si no, podría ser que el tipo de cifrado que usas no lo soporta la librería `ssh2` (quizás actualizando lo arregle).

**Comment by AndresJ551** [comment]
Gracias!

Hice el ssh-add y ahora entró aparentemente.
Se queda en el mensaje "root@192.168.1.1 --getaddrinfo EAI_AGAIN" sin mostrar nada más.

**Comment by AndresJ551** [comment]
Era el parámetro -k, se lo quité y ahora funciona, muchas gracias!
